## 欢迎进入 ModelWhale Notebook  

这里你可以编写代码，文档  

### 关于文件目录  


**project**：project 目录是本项目的工作空间，可以把将项目运行有关的所有文件放在这里，目录中文件的增、删、改操作都会被保留  


**input**：input 目录是数据集的挂载位置，所有挂载进项目的数据集都在这里，未挂载数据集时 input 目录被隐藏  


**temp**：temp 目录是临时磁盘空间，训练或分析过程中产生的不必要文件可以存放在这里，目录中的文件不会保存

In [37]:
import pandas as pd
import matplotlib.pyplot as plt
forest=pd.read_csv("/home/mw/project/fra2020-extentOfForest.csv")
sum_f=forest[["Forest (1990)","Forest (2000)","Forest (2010)","Forest (2020)"]].sum()
print(sum_f)
x=["Forest (1990)","Forest (2000)","Forest (2010)","Forest (2020)"]
#plt.figure(figsize=(10,6))
plt.grid(True)
plt.plot(x,sum_f,marker="s",color='green')
plt.title("1990——2020世界森林面积变化")
plt.fill_between(x, sum_f, min(sum_f), alpha=0.2)
plt.show()
"""
#分析森林增长率前五的结果国家和增长率为负的几个国家
forest.set_index("Country",inplace=True)
cols=forest.columns[:-1]
forest_increase=pd.DataFrame(index=forest.index,columns=cols)
n=len(cols)
print(cols)
for i in range(1,n):
    col_pre=cols[0]
    col_cur=cols[i]
    print(col_pre)
    print(col_cur)
    forest_increase[col_cur]=(forest[col_cur]/forest[col_pre])-1
forest_increase.fillna(0,inplace=True)
#print(forest_increase)

top_five_in=forest_increase.sort_values(by="Forest (2020)",ascending=False).head(5)
top_five_de=forest_increase.sort_values(by="Forest (2020)",ascending=True).head(5)
print(top_five_in)
print(top_five_de)

"""

Forest (1990)    4236433.42
Forest (2000)    4158049.52
Forest (2010)    4106316.94
Forest (2020)    4058930.81
dtype: float64

'\nforest.set_index("Country",inplace=True)\ncols=forest.columns[:-1]\nforest_increase=pd.DataFrame(index=forest.index,columns=cols)\nn=len(cols)\nprint(cols)\nfor i in range(1,n):\n    col_pre=cols[0]\n    col_cur=cols[i]\n    print(col_pre)\n    print(col_cur)\n    forest_increase[col_cur]=(forest[col_cur]/forest[col_pre])-1\nforest_increase.fillna(0,inplace=True)\n#print(forest_increase)\n\ntop_five_in=forest_increase.sort_values(by="Forest (2020)",ascending=False).head(5)\ntop_five_de=forest_increase.sort_values(by="Forest (2020)",ascending=True).head(5)\nprint(top_five_in)\nprint(top_five_de)\n\n'

In [26]:
import pandas as pd
data=pd.read_csv("/home/mw/input/greenhousegas6025/Greenhouse_Gas.csv")
print(data.columns)
name= ['Industry','F2010', 'F2011', 'F2012', 'F2013', 'F2014',
       'F2015', 'F2016', 'F2017', 'F2018', 'F2019', 'F2020', 'F2021']
data1=data[name]      
data1.isnull()

Index(['ObjectId2', 'Country/Region', 'ISO2', 'ISO3', 'Indicator', 'Unit',
       'Source', 'CTS_Code', 'CTS_Name', 'CTS_Full_Descriptor', 'Industry',
       'Gas_Type', 'Scale', 'F2010', 'F2011', 'F2012', 'F2013', 'F2014',
       'F2015', 'F2016', 'F2017', 'F2018', 'F2019', 'F2020', 'F2021'],
      dtype='object')

,Industry,F2010,F2011,F2012,F2013,F2014,F2015,F2016,F2017,F2018,F2019,F2020,F2021
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1109,False,False,False,False,False,False,False,False,False,False,False,False,False
1110,False,False,False,False,False,False,False,False,False,False,False,False,False
1111,False,False,False,False,False,False,False,False,False,False,False,False,False
1112,False,False,False,False,False,False,False,False,False,False,False,False,False
1113,False,False,False,False,False,False,False,False,False,False,False,False,False
1114,False,False,False,False,False,False,False,False,False,False,False,False,False
1115,False,False,False,False,False,False,False,False,False,False,False,False,False
1116,False,False,False,False,False,False,False,False,False,False,False,False,False
1117,False,False,False,False,False,False,False,False,False,False,False,False,False
1118,False,False,False,False,False,False,False,False,False,False,False,False,False
1119,False,False,False,False,False,False,False,False,False,False,False,False,False
1120,False,False,False,False,False,False,False,False,False,False,False,False,False
1121,False,False,False,False,False,False,False,False,False,False,False,False,False
1122,False,False,False,False,False,False,False,False,False,False,False,False,False
1123,False,False,False,False,False,False,False,False,False,False,False,False,False
1124,False,False,False,False,False,False,False,False,False,False,False,False,False
1125,False,False,False,False,False,False,False,False,False,False,False,False,False
1126,False,False,False,False,False,False,False,False,False,False,False,False,False
1127,False,False,False,False,False,False,False,False,False,False,False,False,False
1128,False,False,False,False,False,False,False,False,False,False,False,False,False
1129,False,False,False,False,False,False,False,False,False,False,False,False,False
1130,False,False,False,False,False,False,False,False,False,False,False,False,False
1131,False,False,False,False,False,False,False,False,False,False,False,False,False
1132,False,False,False,False,False,False,False,False,False,False,False,False,False
1133,False,False,False,False,False,False,False,False,False,False,False,False,False
1134,False,False,False,False,False,False,False,False,False,False,False,False,False
1135,False,False,False,False,False,False,False,False,False,False,False,False,False
1136,False,False,False,False,False,False,False,False,False,False,False,False,False
1137,False,False,False,False,False,False,False,False,False,False,False,False,False
1138,False,False,False,False,False,False,False,False,False,False,False,False,False

In [4]:
#画出全球各行业的温室气体排放图的柱状图
import pandas as pd
import matplotlib.pyplot as pl
import pandas as pd
data=pd.read_csv("/home/mw/input/greenhousegas6025/Greenhouse_Gas.csv")
column_world=['Country/Region','Industry', 'F2010', 'F2011', 'F2012', 'F2013', 'F2014',
       'F2015', 'F2016', 'F2017', 'F2018', 'F2019', 'F2020', 'F2021']
data_process=data[column_world]
temp=[]
v=data_process.values
temp=[]
for item in v:
    if item[0]=="World":
        temp.append(item)
data_world=pd.DataFrame(columns=column_world,data=temp)

#print(data_world)
#计算每一个行业每年温室气体排放总量
n=int(len(data_world)/5)
temp1=[]
industrys=[]
for i in range(n):
    start=i*5
    end=(i+1)*5
    industry_name=data_world.iloc[start:start+1,1]
    industrys.append(industry_name.values)
    #print(data_world.iloc[i*5:(i+1)*5,2:])
    #求总排放量
    #print(industry_name)
    sum_number=data_world.iloc[start:end,2:].sum()
    #print(sum_number)
    temp1.append(sum_number)

final_data=pd.DataFrame(columns=['F2010', 'F2011', 'F2012', 'F2013', 'F2014',
       'F2015', 'F2016', 'F2017', 'F2018', 'F2019', 'F2020', 'F2021'],data=temp1)
#print(final_data)
print(final_data)
final_data.to_csv("./data.csv")
bar_temp=final_data.plot.bar(rot=0, figsize=(10, 6), width=0.9)
# 自定义横轴标签及其位置
bar_temp.set_xticks(range(len(final_data.index)))
for x in industrys:
    print(x[0])
bar_temp.set_xticklabels(industrys)

# 设置 x 轴标签的角度、字体大小和距离
pl.xticks(rotation=45, fontsize=12, ha='right')
pl.title("2010到2021年世界各行业温室气体的排放总量变化")
pl.show()

          F2010         F2011         F2012         F2013         F2014  \
0  12097.175693  12213.956992  12210.058272  12426.821452  12473.409754
1   4738.651368   4895.878808   4951.462290   5007.158464   5032.338720
2  24811.912066  25884.989657  26508.803460  26938.682713  27180.727219
3  17647.707476  18439.163059  18812.000514  18696.379079  18972.632208
4   6298.097004   6533.482056   6590.183317   6624.600752   6658.441724
5   5337.011197   5361.474414   5418.168878   5587.396004   5650.134914
6   9857.648187   9858.445624   9987.285324  10241.068644  10315.751586
7  91025.660661  93647.236385  95091.048656  96315.178961  97281.719743
8   5532.544176   5653.013946   5698.305809   5817.660348   5932.548204
9   4704.913505   4806.831833   4914.780786   4975.411504   5065.735415

          F2015         F2016         F2017          F2018          F2019  \
0  12576.561279  12663.757826  12739.356415   12806.859166   12827.106226
1   5058.434975   4961.721522   4962.805816    5062.011654    5186.209170
2  26558.081182  26703.056015  27296.926720   28152.838640   27911.041860
3  18654.633663  18702.177306  18964.064617   19389.926875   19610.993888
4   6508.245690   6297.713158   6369.858900    6558.567385    6670.182524
5   5852.273280   5873.598360   5970.899408    5996.209970    5980.116929
6  10427.441074  10490.917948  10690.897592   10714.841108   10705.010954
7  96925.401885  97131.586225  98784.466399  100779.908441  101128.198606
8   6151.844802   6240.872796   6496.372670    6692.780180    6737.755254
9   5137.885940   5197.771300   5293.284270    5405.873453    5499.781797

          F2020          F2021
0  12920.334728   13068.786406
1   5173.766050    5421.269817
2  26988.563097   28487.441193
3  19474.288582   20223.893095
4   6495.888888    6735.295927
5   5659.493714    5962.268715
6   9811.903130   10423.576443
7  97873.941494  102122.130362
8   5744.162785    6125.260720
9   5605.540516    5674.338046
Agriculture, Forestry and Fishing
Construction
Electricity, Gas, Steam and Air Conditioning Supply
Manufacturing
Mining
Other Services Industries
Total Households
Total Industry and Households
Transportation and Storage
Water supply; sewerage, waste management and remediation activities

In [38]:
import pandas as pd
import matplotlib.pyplot as plt
from math import pi
#读取数据并转换成dataFrame
df = pd.read_csv("/home/mw/project/data.csv", index_col=0)
df = df.transpose()
#创建画布
fig = plt.figure(figsize=(8, 8))
ax = fig.add_subplot(111, polar=True)
#获取角度和标签
categories = list(df)
N = len(categories)
angles = [n / float(N) * 2 * pi for n in range(N)]
angles += angles[:1]
#绘制每个国家的雷达图
for i, row in df.iterrows():
    values = df.loc[i].values.flatten().tolist()
    values += values[:1]
    ax.plot(angles, values, linewidth=1, linestyle='solid', label=i)
    ax.fill(angles, values, 'b', alpha=0.1)
#添加图例和标签
plt.xticks(angles[:-1], categories, color='grey', size=10)
ax.set_rlabel_position(0)
plt.yticks([5000, 10000, 15000, 20000], ["5000", "10000", "15000", "20000"], color="grey", size=8)
plt.ylim(0, 25000)
plt.legend(loc='lower right', bbox_to_anchor=(0.1, 0.1))
plt.title("雷达图", size=20, y=1.1)
plt.show()

In [20]:
import pandas as pd

# 亚洲
asia_countries = ['AFG', 'ARM', 'AZE', 'BHR', 'BGD', 'BTN', 'BRN', 'KHM', 'CHN', 'CXR', 'CCK', 'TLS', 'GEO', 'HKG', 'IND', 'IDN', 'IRN', 'IRQ', 'ISR', 'JPN', 'JOR', 'KAZ', 'KWT', 'KGZ', 'LAO', 'LBN', 'MAC', 'MYS', 'MDV', 'MNG', 'MMR', 'NPL', 'PRK', 'OMN', 'PAK', 'PSE', 'PHL', 'QAT', 'RUS', 'SAU', 'SGP', 'KOR', 'LKA', 'SYR', 'TWN', 'TJK', 'THA', 'TUR', 'TKM', 'ARE', 'UZB', 'VNM', 'YEM']
# 欧洲
europe_countries = ['ALA', 'ALB', 'AND', 'AUT', 'BLR', 'BEL', 'BIH', 'BGR', 'HRV', 'CYP', 'CZE', 'DNK', 'EST', 'FRO', 'FIN', 'FRA', 'GIB', 'DEU', 'GIB', 'GRC', 'VAT', 'HUN', 'ISL', 'IRL', 'IMN', 'ITA', 'JEY', 'KOS', 'LVA', 'LIE', 'LTU', 'LUX', 'MKD', 'MLT', 'MDA', 'MCO', 'MNE', 'NLD', 'NOR', 'POL', 'PRT', 'ROU', 'RUS', 'SMR', 'SRB', 'SVK', 'SVN', 'ESP', 'SJM', 'SWE', 'CHE', 'UKR', 'GBR']

# 非洲
africa_countries =['DZA', 'AGO', 'BEN', 'BFA', 'BDI', 'CMR', 'CPV', 'CAF', 'TCD', 'COM', 'COD', 'DJI', 'EGY', 'GNQ', 'ERI', 'ETH', 'GAB', 'GMB', 'GHA', 'GIN', 'GNB', 'CIV', 'KEN', 'LSO', 'LBR', 'LBY', 'MDG', 'MWI', 'MLI', 'MRT', 'MUS', 'MYT', 'MAR', 'MOZ', 'NAM', 'NER', 'NGA', 'COD', 'REU', 'RWA', 'STP', 'SEN', 'SYC', 'SLE', 'SOM', 'ZAF', 'SSD', 'SHN', 'SDN', 'SZL', 'TZA', 'TGO', 'TUN', 'UGA', 'ESH', 'ZMB', 'ZWE']

# 北美洲
north_america_countries =['AIA', 'ATG', 'ABW', 'BHS', 'BRB', 'BLZ', 'BMU', 'CAN', 'CYM', 'CRI', 'CUB', 'CUW', 'DMA', 'DOM', 'SLV', 'GRL', 'GRD', 'GLP', 'GTM', 'HTI', 'HND', 'JAM', 'MTQ', 'MEX', 'MSR', 'ANT', 'CUW', 'NIC', 'PAN', 'PRI', 'BLM', 'KNA', 'LCA', 'MAF', 'SPM', 'VCT', 'TTO', 'TCA', 'USA', 'VIR']

# 南美洲
south_america_countries = ['ARG', 'BOL', 'BRA', 'CHL', 'COL', 'ECU', 'FLK', 'GUF', 'GUY', 'PRY', 'PER', 'SUR', 'URY', 'VEN']

# 大洋洲
oceania_countries = ['ASM', 'AUS', 'COK', 'FJI', 'PYF', 'GUM', 'KIR', 'MHL', 'FSM', 'NRU', 'NCL', 'NZL', 'NIU', 'NFK', 'MNP', 'PLW', 'PNG', 'PCN', 'WSM', 'SLB', 'TKL', 'TON', 'TUV', 'VUT', 'WLF']
continents={}
continents["asia_countries"]=asia_countries
continents["europe_countries"]=europe_countries
continents["africa_countries"]=africa_countries
continents["north_america_countries"]=north_america_countries
continents["south_america_countries "]=south_america_countries 
continents["oceania_countries"]=oceania_countries

#把国家添加所在洲这一属性
temp=pd.read_csv("/home/mw/input/temp6990/Temp.csv")
"""
sort=temp['ISO3']
CR=set()
for x in sort:
    CR.add(x)
print(CR)
print(len(CR))
"""
temp_data=temp.values
continent_df=[]
#增加洲名属性
flag=1
all=[]
for k,v in continents.items():
    for z in v:
        all.append(z)

for x in temp_data:
    name_ISO3=x[3]
    if name_ISO3 not in all:
        continent_df.append("others")
    else:
        for k,v in continents.items():
            if name_ISO3 in v:
                continent_df.append(k)
                break
print(temp.shape[0])
temp["continent"]=continent_df
print(temp.values)
"""
#绘制地图
import pandas as pd
import plotly.express as px
# 读取数据文件
data = pd.read_csv('/home/mw/input/temp6990/Temp.csv')

# 使用 plotly 中的 Choropleth 类型绘制地图
fig = px.choropleth(data,  # 数据集
                    locations='ISO3',  # 国家简称列
                    color='F2010',  # 温度列
                    hover_name='Country/Region',  # 悬停显示国家名称
                    color_continuous_scale=px.colors.sequential.Plasma)
# 显示地图
fig.show()
"""

227
[[1 'Afghanistan, Islamic Rep. of' 'AF' ... 0.544 1.421 'asia_countries']
 [2 'Albania' 'AL' ... 1.6230000000000002 1.682 'europe_countries']
 [3 'Algeria' 'DZ' ... 1.913 2.3169999999999997 'africa_countries']
 ...
 [225 'Yemen, Rep. of' 'YE' ... nan nan 'asia_countries']
 [226 'Zambia' 'ZM' ... 1.252 1.002 'africa_countries']
 [230 'Zimbabwe' 'ZW' ... 0.415 -0.10099999999999999 'africa_countries']]

ModuleNotFoundError: No module named 'plotly.express'

In [1]:
import pandas as pd
import numpy as np
#各大洲平均气温变化
data4=pd.read_csv('/home/mw/project/self_ghg_gas_原始数据集.csv').values
#print(pd.read_csv('/home/mw/project/self_ghg_gas_原始数据集.csv').columns)
data5=[]
for n in data4:
    if n[1] in ['Asia','Europe','Africa','North America','South America','Oceania','Antarctica']:
        data5.append(n)

data5=pd.DataFrame(columns=pd.read_csv('/home/mw/project/self_ghg_gas_原始数据集.csv').columns,data=data5)
#print(data5)
name0=['population', 'gdp',
       'cement_co2', 'cement_co2_per_capita', 'co2', 'co2_growth_abs',
       'co2_growth_prct', 'co2_including_luc', 'co2_including_luc_growth_abs',
       'co2_including_luc_growth_prct', 'co2_including_luc_per_capita',
       'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy',
       'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2',
       'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita',
       'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2',
       'cumulative_co2_including_luc', 'cumulative_coal_co2',
       'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2',
       'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita',
       'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2',
       'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita',
       'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane',
       'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita',
       'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita',
       'other_industry_co2', 'primary_energy_consumption',
       'share_global_cement_co2', 'share_global_co2',
       'share_global_co2_including_luc', 'share_global_coal_co2',
       'share_global_cumulative_cement_co2', 'share_global_cumulative_co2',
       'share_global_cumulative_co2_including_luc',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2',
       'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2',
       'share_global_flaring_co2', 'share_global_gas_co2',
       'share_global_luc_co2', 'share_global_oil_co2',
       'share_global_other_co2', 'share_of_temperature_change_from_ghg',
       'temperature_change_from_ch4', 'temperature_change_from_co2',
       'temperature_change_from_ghg', 'temperature_change_from_n2o',
       'total_ghg', 'total_ghg_excluding_lucf', 'trade_co2',
       'trade_co2_share']
"""
def is_all_nan(element):
    temp=element.isnull()
    n=len(temp)
    count=0
    for x in temp:
        if x=="false":
            count=count+1
    if count==n:
        return True
    else:
        return False
"""
def is_all_nan(arr):
    """判断一个数组是否全为NaN值或者部分NAN"""
    nan_count = np.sum(np.isnan(arr))
    if nan_count!=0 and nan_count <= arr.size*0.2:
        return True
    else:
        return False

for i in range(0,6):
    start=i*21
    end=(i+1)*21
    for name00 in name0:
        if is_all_nan(data5[name00][start:end]):
            x=data5[name00][start:end].mean(axis=0)
            data5[name00][start:end]=data5[name00][start:end].fillna(x)
print(data5)
data5.to_csv("./self_处理v1.csv")

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

     Unnamed: 0        country  year  iso_code    population  gdp  cement_co2  \
0            21         Africa  2000       NaN  8.189524e+08  NaN      31.310
1            22         Africa  2001       NaN  8.394641e+08  NaN      32.762
2            23         Africa  2002       NaN  8.606118e+08  NaN      35.178
3            24         Africa  2003       NaN  8.823496e+08  NaN      35.452
4            25         Africa  2004       NaN  9.047816e+08  NaN      38.115
5            26         Africa  2005       NaN  9.278984e+08  NaN      41.906
6            27         Africa  2006       NaN  9.517406e+08  NaN      45.721
7            28         Africa  2007       NaN  9.764617e+08  NaN      49.050
8            29         Africa  2008       NaN  1.001982e+09  NaN      51.576
9            30         Africa  2009       NaN  1.028201e+09  NaN      57.764
10           31         Africa  2010       NaN  1.055234e+09  NaN      59.311
11           32         Africa  2011       NaN  1.082676e+09  NaN      59.080
12           33         Africa  2012       NaN  1.110797e+09  NaN      63.726
13           34         Africa  2013       NaN  1.140181e+09  NaN      66.163
14           35         Africa  2014       NaN  1.170299e+09  NaN      70.076
15           36         Africa  2015       NaN  1.201108e+09  NaN      73.669
16           37         Africa  2016       NaN  1.232112e+09  NaN      77.765
17           38         Africa  2017       NaN  1.263334e+09  NaN      77.602
18           39         Africa  2018       NaN  1.295265e+09  NaN      80.124
19           40         Africa  2019       NaN  1.327701e+09  NaN      80.359
20           41         Africa  2020       NaN  1.360677e+09  NaN      79.000
21          273           Asia  2000       NaN  3.735090e+09  NaN     464.483
22          274           Asia  2001       NaN  3.785215e+09  NaN     498.792
23          275           Asia  2002       NaN  3.834687e+09  NaN     536.806
24          276           Asia  2003       NaN  3.883311e+09  NaN     588.314
25          277           Asia  2004       NaN  3.931403e+09  NaN     633.244
26          278           Asia  2005       NaN  3.979345e+09  NaN     675.255
27          279           Asia  2006       NaN  4.027292e+09  NaN     745.681
28          280           Asia  2007       NaN  4.074998e+09  NaN     809.072
29          281           Asia  2008       NaN  4.122807e+09  NaN     835.241
..          ...            ...   ...       ...           ...  ...         ...
96         3435        Oceania  2012       NaN  3.838377e+07  NaN       4.134
97         3436        Oceania  2013       NaN  3.905778e+07  NaN       3.926
98         3437        Oceania  2014       NaN  3.972934e+07  NaN       3.797
99         3438        Oceania  2015       NaN  4.040364e+07  NaN       3.740
100        3439        Oceania  2016       NaN  4.110124e+07  NaN       3.460
101        3440        Oceania  2017       NaN  4.181727e+07  NaN       3.503
102        3441        Oceania  2018       NaN  4.254003e+07  NaN       3.393
103        3442        Oceania  2019       NaN  4.327847e+07  NaN       3.480
104        3443        Oceania  2020       NaN  4.393376e+07  NaN       3.229
105        4242  South America  2000       NaN  3.496343e+08  NaN      31.027
106        4243  South America  2001       NaN  3.544752e+08  NaN      29.918
107        4244  South America  2002       NaN  3.591771e+08  NaN      27.623
108        4245  South America  2003       NaN  3.637054e+08  NaN      27.610
109        4246  South America  2004       NaN  3.681269e+08  NaN      27.439
110        4247  South America  2005       NaN  3.725025e+08  NaN      30.410
111        4248  South America  2006       NaN  3.767884e+08  NaN      34.762
112        4249  South America  2007       NaN  3.809660e+08  NaN      36.155
113        4250  South America  2008       NaN  3.850314e+08  NaN      38.344
114        4251  South America  2009       NaN  3.890453e+08  NaN      38.052
115        4252  South America  2010       NaN  3.930783e+08  NaN      40.340
116        4253  South America  2011       NaN  3.971352e+08  NaN      43.338
117        4254  South America  2012       NaN  4.011669e+08  NaN      46.479
118        4255  South America  2013       NaN  4.051480e+08  NaN      49.248
119        4256  South America  2014       NaN  4.091289e+08  NaN      49.797
120        4257  South America  2015       NaN  4.131345e+08  NaN      48.401
121        4258  South America  2016       NaN  4.171018e+08  NaN      43.920
122        4259  South America  2017       NaN  4.209826e+08  NaN      40.529
123        4260  South America  2018       NaN  4.247407e+08  NaN      40.776
124        4261  South America  2019       NaN  4.283182e+08  NaN      41.567
125        4262  South America  2020       NaN  4.315301e+08  NaN      42.353

     cement_co2_per_capita        co2  co2_growth_abs  ...  \
0                    0.038    886.403          55.992  ...
1                    0.039    884.000          -2.403  ...
2                    0.041    892.559           8.559  ...
3                    0.040    967.170          74.611  ...
4                    0.042   1036.637          69.467  ...
5                    0.045   1057.361          20.724  ...
6                    0.048   1090.145          32.784  ...
7                    0.050   1132.287          42.142  ...
8                    0.051   1181.175          48.887  ...
9                    0.056   1171.780          -9.395  ...
10                   0.056   1214.749          42.969  ...
11                   0.055   1251.306          36.557  ...
12                   0.057   1259.537           8.231  ...
13                   0.058   1268.892           9.355  ...
14                   0.060   1350.089          81.197  ...
15                   0.061   1323.759         -26.330  ...
16                   0.063   1363.459          39.700  ...
17                   0.061   1379.490          16.031  ...
18                   0.062   1366.411         -13.079  ...
19                   0.061   1467.492         101.081  ...
20                   0.058   1385.889         -81.602  ...
21                   0.124   9300.388         420.007  ...
22                   0.132   9465.591         165.203  ...
23                   0.140  10011.630         546.039  ...
24                   0.152  10993.296         981.667  ...
25                   0.161  11682.221         688.925  ...
26                   0.170  12525.167         842.946  ...
27                   0.185  13366.732         841.566  ...
28                   0.199  14076.581         709.848  ...
29                   0.203  14819.766         743.184  ...
..                     ...        ...             ...  ...
96                   0.108    454.100           3.885  ...
97                   0.101    445.829          -8.271  ...
98                   0.096    444.417          -1.412  ...
99                   0.093    452.418           8.001  ...
100                  0.085    461.105           8.687  ...
101                  0.084    465.584           4.479  ...
102                  0.080    468.674           3.090  ...
103                  0.081    470.359           1.685  ...
104                  0.074    452.186         -18.174  ...
105                  0.089    821.225         -18.088  ...
106                  0.084    832.130          10.905  ...
107                  0.077    847.045          14.915  ...
108                  0.076    858.202          11.157  ...
109                  0.075    867.599           9.396  ...
110                  0.082    901.994          34.396  ...
111                  0.092    912.943          10.949  ...
112                  0.095    940.783          27.840  ...
113                  0.100   1007.551          66.768  ...
114                  0.098    991.982         -15.569  ...
115                  0.103   1082.467          90.485  ...
116                  0.109   1104.313          21.846  ...
117                  0.116   1144.498          40.185  ...
118                  0.122   1209.994          65.496  ...
119                  0.122   1229.192          19.198  ...
120                  0.117   1193.827         -35.365  ...
121                  0.105   1152.788         -41.039  ...
122                  0.096   1125.113         -27.675  ...
123                  0.096   1064.608         -60.505  ...
124                  0.097   1073.178           8.570  ...
125                  0.098    981.190         -91.989  ...

     share_global_other_co2  share_of_temperature_change_from_ghg  \
0                       NaN                                 8.746
1                       NaN                                 8.794
2                       NaN                                 8.834
3                       NaN                                 8.879
4                       NaN                                 8.922
5                       NaN                                 8.963
6                       NaN                                 8.995
7                       NaN                                 9.027
8                       NaN                                 9.065
9                       NaN                                 9.099
10                      NaN                                 9.131
11                      NaN                                 9.158
12                      NaN                                 9.183
13                      NaN                                 9.202
14                      NaN                                 9.211
15                      NaN                                 9.210
16                      NaN                                 9.206
17                      NaN                                 9.206
18                      NaN                                 9.202
19                      NaN                                 9.196
20                      NaN                                 9.191
21                   51.207                                28.576
22                   51.085                                28.791
23                   51.266                                29.025
24                   51.840                                29.268
25                   51.964                                29.526
26                   53.655                                29.805
27                   54.206                                30.116
28                   55.189                                30.421
29                   56.581                                30.735
..                      ...                                   ...
96                    1.653                                 2.073
97                    1.430                                 2.057
98                    1.544                                 2.043
99                    1.561                                 2.028
100                   1.526                                 2.014
101                   1.490                                 2.002
102                   1.491                                 1.989
103                   1.477                                 1.971
104                   1.454                                 1.952
105                   2.316                                 9.111
106                   2.258                                 9.130
107                   2.297                                 9.154
108                   2.298                                 9.196
109                   2.383                                 9.232
110                   2.215                                 9.259
111                   2.142                                 9.273
112                   2.185                                 9.280
113                   2.192                                 9.281
114                   2.077                                 9.281
115                   2.419                                 9.276
116                   2.306                                 9.260
117                   2.318                                 9.245
118                   2.205                                 9.230
119                   2.059                                 9.209
120                   2.111                                 9.185
121                   2.130                                 9.161
122                   2.114                                 9.130
123                   2.113                                 9.091
124                   2.085                                 9.056
125                   2.157                                 9.021

     temperature_change_from_ch4  temperature_change_from_co2  \
0                          0.040                        0.052
1                          0.041                        0.053
2                          0.042                        0.054
3                          0.043                        0.055
4                          0.045                        0.056
5                          0.046                        0.057
6                          0.047                        0.058
7                          0.048                        0.059
8                          0.049                        0.060
9                          0.050                        0.062
10                         0.051                        0.063
11                         0.052                        0.064
12                         0.053                        0.066
13                         0.054                        0.067
14                         0.055                        0.068
15                         0.056                        0.070
16                         0.056                        0.071
17                         0.057                        0.072
18                         0.058                        0.073
19                         0.059                        0.075
20                         0.059                        0.076
21                         0.124                        0.184
22                         0.126                        0.189
23                         0.128                        0.194
24                         0.131                        0.200
25                         0.134                        0.206
26                         0.137                        0.212
27                         0.140                        0.219
28                         0.143                        0.226
29                         0.146                        0.233
..                           ...                          ...
96                         0.010                        0.016
97                         0.010                        0.016
98                         0.010                        0.016
99                         0.010                        0.016
100                        0.010                        0.017
101                        0.010                        0.017
102                        0.010                        0.017
103                        0.010                        0.017
104                        0.010                        0.017
105                        0.034                        0.066
106                        0.034                        0.067
107                        0.035                        0.068
108                        0.036                        0.070
109                        0.036                        0.071
110                        0.037                        0.073
111                        0.038                        0.074
112                        0.038                        0.075
113                        0.039                        0.077
114                        0.039                        0.078
115                        0.040                        0.079
116                        0.041                        0.081
117                        0.041                        0.082
118                        0.042                        0.083
119                        0.042                        0.085
120                        0.043                        0.086
121                        0.043                        0.087
122                        0.044                        0.088
123                        0.044                        0.089
124                        0.045                        0.090
125                        0.045                        0.091

     temperature_change_from_ghg  temperature_change_from_n2o   total_ghg  \
0                          0.099                        0.007   2580.8300
1                          0.101                        0.007   2690.3900
2                          0.104                        0.007   2734.8900
3                          0.106                        0.007   2857.5400
4                          0.108                        0.008   2922.4100
5                          0.111                        0.008   3027.3800
6                          0.113                        0.008   3034.3000
7                          0.115                        0.008   3119.1100
8                          0.118                        0.008   3217.0000
9                          0.120                        0.008   3187.5300
10                         0.123                        0.009   3319.5500
11                         0.125                        0.009   3263.8400
12                         0.128                        0.009   3381.3000
13                         0.130                        0.009   3406.0700
14                         0.132                        0.009   3453.8800
15                         0.135                        0.010   3481.9300
16                         0.137                        0.010   3583.3600
17                         0.139                        0.010   3643.5700
18                         0.141                        0.010   3688.8300
19                         0.144                        0.010   3745.8800
20                         0.146                        0.011   3216.9795
21                         0.324                        0.017  12472.6410
22                         0.332                        0.017  12721.6600
23                         0.340                        0.018  13692.3700
24                         0.349                        0.018  14216.1400
25                         0.358                        0.019  15691.9200
26                         0.368                        0.019  16404.8200
27                         0.378                        0.020  17789.4390
28                         0.388                        0.020  18249.1890
29                         0.399                        0.021  18745.7300
..                           ...                          ...         ...
96                         0.029                        0.004    746.8800
97                         0.029                        0.004    662.5200
98                         0.029                        0.004    679.9900
99                         0.030                        0.004    681.5100
100                        0.030                        0.004    760.1700
101                        0.030                        0.004    810.3600
102                        0.031                        0.004    804.9700
103                        0.031                        0.004    793.5700
104                        0.031                        0.004    738.8890
105                        0.103                        0.004   3343.9300
106                        0.105                        0.004   3388.7400
107                        0.107                        0.004   3421.8300
108                        0.110                        0.004   3450.9100
109                        0.112                        0.004   3557.8000
110                        0.114                        0.005   3591.7400

In [16]:
#画一个图看一下
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as stam
handle_csv=pd.read_csv("./self_处理v1.csv")
new_data=handle_csv.loc[:,["country","temperature_change_from_ghg"]]
handle_data=new_data.values
#print(handle_data)

n=21
count=0
temps=[]
A=[]
continents=[]
for x in handle_data:
    A.append(x[1])
    count=count+1
    if count%21==0:
        continents.append(x[0])
        temps.append(A)
        A=[]
#print(temps)
print(continents)
year=['2000',"2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020"]
m=len(continents)
marks=["h","s","^","x","o","d"]
plt.figure(figsize=(10,6))
plt.grid(True)
for i in range(m):
    x=year
    y=temps[i]
    plt.plot(x,y,marker=marks[i],label=continents[i])
plt.title("2000年到2020年各洲温室气体排放引起的温度变化")
plt.legend()
plt.xticks(rotation=45)
plt.show()

#分析各个国家二氧化碳、甲烷、一氧化二氮排放量与因温室气体温度升高的相关性
t_df=pd.read_csv("/home/mw/project/Temp000.csv")

"""
# 读取数据
df = pd.read_csv('/home/mw/project/self_ghg_处理V2.csv')
# 删除 CO2、CH4、N2O、temperature 四列中任意一列为空的行，并返回新 DataFrame
df_new = df.dropna(subset=["methane","co2","nitrous_oxide",'temperature_change_from_ghg'])
"""
corr_matrix =handle_csv[["methane","co2","nitrous_oxide",'temperature_change_from_ghg']].corr(method='pearson')
print(corr_matrix)
#多元回归分析
df = pd.read_csv('/home/mw/project/self_ghg_处理V2.csv')
# 删除 CO2、CH4、N2O、temperature 四列中任意一列为空的行，并返回新 DataFrame
df_new = df.dropna(subset=["methane","co2","nitrous_oxide",'temperature_change_from_ghg'])
x1=df_new[["methane","co2","nitrous_oxide"]]
y1=df_new[['temperature_change_from_ghg']]
x1=stam.add_constant(x1)
model=stam.OLS(y1,x1).fit()
print(model.summary())

['Africa', 'Asia', 'Europe', 'North America', 'Oceania', 'South America']

                              methane       co2  nitrous_oxide  \
methane                      1.000000  0.907259       0.983227
co2                          0.907259  1.000000       0.878925
nitrous_oxide                0.983227  0.878925       1.000000
temperature_change_from_ghg  0.793856  0.918100       0.755718

                             temperature_change_from_ghg
methane                                         0.793856
co2                                             0.918100
nitrous_oxide                                   0.755718
temperature_change_from_ghg                     1.000000
                                 OLS Regression Results
=======================================================================================
Dep. Variable:     temperature_change_from_ghg   R-squared:                       0.790
Model:                                     OLS   Adj. R-squared:                  0.790
Method:                          Least Squares   F-statistic:                     5022.
Date:                         Tue, 30 May 2023   Prob (F-statistic):               0.00
Time:                                 09:13:51   Log-Likelihood:                 12540.
No. Observations:                         4011   AIC:                        -2.507e+04
Df Residuals:                             4007   BIC:                        -2.505e+04
Df Model:                                    3
Covariance Type:                     nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             0.0013      0.000      7.387      0.000       0.001       0.002
methane           0.0001   3.91e-06     28.038      0.000       0.000       0.000
co2            1.976e-05   5.22e-07     37.843      0.000    1.87e-05    2.08e-05
nitrous_oxide    -0.0001   1.19e-05    -11.306      0.000      -0.000      -0.000
==============================================================================
Omnibus:                     3745.566   Durbin-Watson:                   0.097
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           995731.180
Skew:                           3.774   Prob(JB):                         0.00
Kurtosis:                      79.818   Cond. No.                         835.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [28]:
import pandas as pd
import numpy as np
whole_relate=pd.read_csv('/home/mw/project/self_ghg_gas_原始数据集.csv')
not_continent=[]
ISO_not_null=whole_relate["iso_code"].notna()#返回ISO不为空的行号
result=whole_relate[ISO_not_null]
name0=['population', 'gdp',
       'cement_co2', 'cement_co2_per_capita', 'co2', 'co2_growth_abs',
       'co2_growth_prct', 'co2_including_luc', 'co2_including_luc_growth_abs',
       'co2_including_luc_growth_prct', 'co2_including_luc_per_capita',
       'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy',
       'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2',
       'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita',
       'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2',
       'cumulative_co2_including_luc', 'cumulative_coal_co2',
       'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2',
       'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita',
       'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2',
       'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita',
       'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane',
       'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita',
       'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita',
       'other_industry_co2', 'primary_energy_consumption',
       'share_global_cement_co2', 'share_global_co2',
       'share_global_co2_including_luc', 'share_global_coal_co2',
       'share_global_cumulative_cement_co2', 'share_global_cumulative_co2',
       'share_global_cumulative_co2_including_luc',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2',
       'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2',
       'share_global_flaring_co2', 'share_global_gas_co2',
       'share_global_luc_co2', 'share_global_oil_co2',
       'share_global_other_co2', 'share_of_temperature_change_from_ghg',
       'temperature_change_from_ch4', 'temperature_change_from_co2',
       'temperature_change_from_ghg', 'temperature_change_from_n2o',
       'total_ghg', 'total_ghg_excluding_lucf', 'trade_co2',
       'trade_co2_share']
def is_all_nan(arr):
    """判断一个数组是否全为NaN值或者部分NAN"""
    nan_count = np.sum(np.isnan(arr))
    if nan_count!=0 and nan_count <= arr.size*0.2:
        return True
    else:
        return False
#计算国家的数量
temp_c=result.values
countries=set()
for x in temp_c:
    countries.add(x[1])
n=len(countries)
#数据预处理
for i in range(0,n):
    start=i*21
    end=(i+1)*21
    for name00 in name0:
        if is_all_nan(result[name00][start:end]):
            x=result[name00][start:end].mean(axis=0)
            result[name00][start:end]=result[name00][start:end].fillna(x)
print(result)
result.to_csv("/home/mw/project/self_ghg_处理V2.csv")
#聚类分析

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

      Unnamed: 0      country  year iso_code  population           gdp  \
0              0  Afghanistan  2000      AFG  19542986.0  1.128379e+10
1              1  Afghanistan  2001      AFG  19688634.0  1.102127e+10
2              2  Afghanistan  2002      AFG  21000258.0  1.880487e+10
3              3  Afghanistan  2003      AFG  22645136.0  2.107434e+10
4              4  Afghanistan  2004      AFG  23553554.0  2.233257e+10
5              5  Afghanistan  2005      AFG  24411196.0  2.539769e+10
6              6  Afghanistan  2006      AFG  25442946.0  2.870440e+10
7              7  Afghanistan  2007      AFG  25903306.0  3.450753e+10
8              8  Afghanistan  2008      AFG  26427204.0  3.656104e+10
9              9  Afghanistan  2009      AFG  27385310.0  4.435872e+10
10            10  Afghanistan  2010      AFG  28189672.0  4.739942e+10
11            11  Afghanistan  2011      AFG  29249156.0  5.332634e+10
12            12  Afghanistan  2012      AFG  30466484.0  5.916690e+10
13            13  Afghanistan  2013      AFG  31541216.0  6.299370e+10
14            14  Afghanistan  2014      AFG  32716214.0  6.434611e+10
15            15  Afghanistan  2015      AFG  33753500.0  6.278339e+10
16            16  Afghanistan  2016      AFG  34636212.0  6.429743e+10
17            17  Afghanistan  2017      AFG  35643420.0  6.875280e+10
18            18  Afghanistan  2018      AFG  36686788.0  6.759497e+10
19            19  Afghanistan  2019      AFG  37769496.0  4.235302e+10
20            20  Afghanistan  2020      AFG  38972236.0  4.235302e+10
63            63      Albania  2000      ALB   3182027.0  1.521426e+10
64            64      Albania  2001      ALB   3153615.0  1.656384e+10
65            65      Albania  2002      ALB   3123554.0  1.740807e+10
66            66      Albania  2003      ALB   3092993.0  1.846550e+10
67            67      Albania  2004      ALB   3062629.0  1.958788e+10
68            68      Albania  2005      ALB   3032636.0  2.078108e+10
69            69      Albania  2006      ALB   3003391.0  2.212429e+10
70            70      Albania  2007      ALB   2976089.0  2.357465e+10
71            71      Albania  2008      ALB   2951690.0  2.547694e+10
...          ...          ...   ...      ...         ...           ...
5052        5052       Zambia  2012      ZMB  14744662.0  4.856737e+10
5053        5053       Zambia  2013      ZMB  15234976.0  5.101969e+10
5054        5054       Zambia  2014      ZMB  15737796.0  5.341918e+10
5055        5055       Zambia  2015      ZMB  16248231.0  5.498018e+10
5056        5056       Zambia  2016      ZMB  16767758.0  5.661833e+10
5057        5057       Zambia  2017      ZMB  17298056.0  5.861356e+10
5058        5058       Zambia  2018      ZMB  17835898.0  6.097862e+10
5059        5059       Zambia  2019      ZMB  18380478.0  3.725467e+10
5060        5060       Zambia  2020      ZMB  18927716.0  3.725467e+10
5061        5061     Zimbabwe  2000      ZWE  11834679.0  2.676498e+10
5062        5062     Zimbabwe  2001      ZWE  11910981.0  2.678117e+10
5063        5063     Zimbabwe  2002      ZWE  11984643.0  2.487246e+10
5064        5064     Zimbabwe  2003      ZWE  12075835.0  2.095200e+10
5065        5065     Zimbabwe  2004      ZWE  12160885.0  1.979282e+10
5066        5066     Zimbabwe  2005      ZWE  12224758.0  1.844445e+10
5067        5067     Zimbabwe  2006      ZWE  12330490.0  1.804298e+10
5068        5068     Zimbabwe  2007      ZWE  12450566.0  1.776908e+10
5069        5069     Zimbabwe  2008      ZWE  12550353.0  1.505022e+10
5070        5070     Zimbabwe  2009      ZWE  12679812.0  1.627576e+10
5071        5071     Zimbabwe  2010      ZWE  12839774.0  1.791838e+10
5072        5072     Zimbabwe  2011      ZWE  13025789.0  1.955407e+10
5073        5073     Zimbabwe  2012      ZWE  13265331.0  2.090997e+10
5074        5074     Zimbabwe  2013      ZWE  13555420.0  2.112350e+10
5075        5075     Zimbabwe  2014      ZWE  13855758.0  2.122250e+10
5076        5076     Zimbabwe  2015      ZWE  14154937.0  2.102745e+10
5077        5077     Zimbabwe  2016      ZWE  14452705.0  2.096179e+10
5078        5078     Zimbabwe  2017      ZWE  14751101.0  2.194784e+10
5079        5079     Zimbabwe  2018      ZWE  15052191.0  2.271535e+10
5080        5080     Zimbabwe  2019      ZWE  15354606.0  2.063825e+10
5081        5081     Zimbabwe  2020      ZWE  15669663.0  2.063825e+10

      cement_co2  cement_co2_per_capita     co2  co2_growth_abs  ...  \
0          0.010                  0.001   1.047          -0.045  ...
1          0.007                  0.000   1.069           0.022  ...
2          0.011                  0.001   1.341           0.272  ...
3          0.010                  0.000   1.560           0.219  ...
4          0.010                  0.000   1.237          -0.322  ...
5          0.006                  0.000   1.890           0.652  ...
6          0.012                  0.000   2.159           0.270  ...
7          0.012                  0.000   2.800           0.641  ...
8          0.015                  0.001   4.254           1.455  ...
9          0.013                  0.000   6.392           2.137  ...
10         0.015                  0.001   8.365           1.973  ...
11         0.015                  0.000  11.838           3.474  ...
12         0.029                  0.001  10.035          -1.803  ...
13         0.036                  0.001   9.251          -0.785  ...
14         0.029                  0.001   9.170          -0.080  ...
15         0.041                  0.001   9.791           0.621  ...
16         0.076                  0.002   9.068          -0.723  ...
17         0.045                  0.001   9.868           0.800  ...
18         0.057                  0.002  10.818           0.950  ...
19         0.038                  0.001  11.082           0.264  ...
20         0.061                  0.002  11.682           0.600  ...
63         0.094                  0.029   3.025           0.039  ...
64         0.000                  0.000   3.221           0.196  ...
65         0.000                  0.000   3.748           0.528  ...
66         0.302                  0.098   4.303           0.555  ...
67         0.300                  0.098   4.177          -0.127  ...
68         0.256                  0.085   4.261           0.085  ...
69         0.276                  0.092   3.911          -0.351  ...
70         0.468                  0.157   3.949           0.038  ...
71         0.484                  0.164   4.397           0.448  ...
...          ...                    ...     ...             ...  ...
5052       0.612                  0.041   4.166           0.793  ...
5053       0.705                  0.046   4.416           0.250  ...
5054       0.736                  0.047   4.877           0.460  ...
5055       0.697                  0.043   5.065           0.188  ...
5056       0.775                  0.046   5.857           0.792  ...
5057       0.856                  0.050   6.843           0.985  ...
5058       1.066                  0.060   7.412           0.569  ...
5059       0.961                  0.052   7.747           0.335  ...
5060       0.961                  0.051   7.281          -0.466  ...
5061       0.404                  0.034  13.818          -1.910  ...
5062       0.322                  0.027  12.509          -1.309  ...
5063       0.241                  0.020  11.896          -0.613  ...
5064       0.160                  0.013  10.610          -1.286  ...
5065       0.199                  0.016   9.429          -1.181  ...
5066       0.238                  0.019  10.698           1.270  ...
5067       0.275                  0.022  10.365          -0.333  ...
5068       0.155                  0.012   9.835          -0.530  ...
5069       0.154                  0.012   7.720          -2.115  ...
5070       0.270                  0.021   8.250           0.530  ...
5071       0.308                  0.024   8.754           0.504  ...
5072       0.382                  0.029  10.363           1.609  ...
5073       0.566                  0.043  11.254           0.891  ...
5074       0.463                  0.034  11.671           0.418  ...
5075       0.496                  0.036  11.946           0.275  ...
5076       0.585                  0.041  12.255           0.309  ...
5077       0.461                  0.032  10.533          -1.722  ...
5078       0.469                  0.032   9.596          -0.937  ...
5079       0.558                  0.037  11.795           2.199  ...
5080       0.570                  0.037  11.115          -0.681  ...
5081       0.570                  0.036  10.608          -0.507  ...

      share_global_other_co2  share_of_temperature_change_from_ghg  \
0                        NaN                                 0.080
1                        NaN                                 0.079
2                        NaN                                 0.078
3                        NaN                                 0.078
4                        NaN                                 0.077
5                        NaN                                 0.077
6                        NaN                                 0.077
7                        NaN                                 0.077
8                        NaN                                 0.077
9                        NaN                                 0.078
10                       NaN                                 0.078
11                       NaN                                 0.079
12                       NaN                                 0.080
13                       NaN                                 0.080
14                       NaN                                 0.081
15                       NaN                                 0.081
16                       NaN                                 0.082
17                       NaN                                 0.082
18                       NaN                                 0.082
19                       NaN                                 0.082
20                       NaN                                 0.082
63                       NaN                                 0.031
64                       NaN                                 0.031
65                       NaN                                 0.031
66                       NaN                                 0.030
67                       NaN                                 0.030
68                       NaN                                 0.029
69                       NaN                                 0.029
70                       NaN                                 0.028
71                       NaN                                 0.028
...                      ...                                   ...
5052                     NaN                                 0.224
5053                     NaN                                 0.223
5054                     NaN                                 0.223
5055                     NaN                                 0.222
5056                     NaN                                 0.222
5057                     NaN                                 0.221
5058                     NaN                                 0.220
5059                     NaN                                 0.220
5060                     NaN                                 0.219
5061                     NaN                                 0.121
5062                     NaN                                 0.122
5063                     NaN                                 0.122
5064                     NaN                                 0.122
5065                     NaN                                 0.122
5066                     NaN                                 0.122
5067                     NaN                                 0.122
5068                     NaN                                 0.121
5069                     NaN                                 0.121
5070                     NaN                                 0.120
5071                     NaN                                 0.120
5072                     NaN                                 0.119
5073                     NaN                                 0.118
5074                     NaN                                 0.118
5075                     NaN                                 0.117
5076                     NaN                                 0.116
5077                     NaN                                 0.115
5078                     NaN                                 0.114
5079                     NaN                                 0.114
5080                     NaN                                 0.113
5081                     NaN                                 0.112

      temperature_change_from_ch4  temperature_change_from_co2  \
0                           0.000                        0.000
1                           0.000                        0.000
2                           0.000                        0.000
3                           0.000                        0.000
4                           0.000                        0.000
5                           0.000                        0.000
6                           0.000                        0.000
7                           0.000                        0.000
8                           0.000                        0.000
9                           0.000                        0.000
10                          0.000                        0.000
11                          0.000                        0.000
12                          0.001                        0.000
13                          0.001                        0.000
14                          0.001                        0.000
15                          0.001                        0.000
16                          0.001                        0.000
17                          0.001                        0.000
18                          0.001                        0.001
19                          0.001                        0.001
20                          0.001                        0.001
63                          0.000                        0.000
64                          0.000                        0.000
65                          0.000                        0.000
66                          0.000                        0.000
67                          0.000                        0.000
68                          0.000                        0.000
69                          0.000                        0.000
70                          0.000                        0.000
71                          0.000                        0.000
...                           ...                          ...
5052                        0.001                        0.002
5053                        0.001                        0.002
5054                        0.001                        0.002
5055                        0.001                        0.002
5056                        0.001                        0.002
5057                        0.001                        0.002
5058                        0.001                        0.002
5059                        0.001                        0.002
5060                        0.001                        0.002
5061                        0.000                        0.001
5062                        0.000                        0.001
5063                        0.000                        0.001
5064                        0.001                        0.001
5065                        0.001                        0.001
5066                        0.001                        0.001
5067                        0.001                        0.001
5068                        0.001                        0.001
5069                        0.001                        0.001
5070                        0.001                        0.001
5071                        0.001                        0.001
5072                        0.001                        0.001
5073                        0.001                        0.001
5074                        0.001                        0.001
5075                        0.001                        0.001
5076                        0.001                        0.001
5077                        0.001                        0.001
5078                        0.001                        0.001
5079                        0.001                        0.001
5080                        0.001                        0.001
5081                        0.001                        0.001

      temperature_change_from_ghg  temperature_change_from_n2o  total_ghg  \
0                           0.001                          0.0    11.5000
1                           0.001                          0.0    12.3700
2                           0.001                          0.0    15.0100
3                           0.001                          0.0    15.6500
4                           0.001                          0.0    15.4400
5                           0.001                          0.0    16.3500
6                           0.001                          0.0    16.8700
7                           0.001                          0.0    17.2600
8                           0.001                          0.0    20.6600
9                           0.001                          0.0    22.7500
10                          0.001                          0.0    27.2400
11                          0.001                          0.0    29.1700
12                          0.001                          0.0    28.5500
13                          0.001                          0.0    26.7700
14                          0.001                          0.0    26.5200
15                          0.001                          0.0    26.8400
16                          0.001                          0.0    27.0500
17                          0.001                          0.0    26.6800
18                          0.001                          0.0    27.8400
19                          0.001                          0.0    28.7900
20                          0.001                          0.0    21.9655
63                          0.000                          0.0     8.4000
64                          0.000                          0.0     7.0000
65                          0.000                          0.0     7.6300
66                          0.000                          0.0     7.9700
67                          0.000                          0.0     8.0500
68                          0.000                          0.0     7.8300
69                          0.000                          0.0     7.7300
70                          0.000                          0.0     7.7500
71                          0.000                          0.0     7.4800
...                           ...                          ...        ...
5052                        0.003                          0.0    85.1500
5053                        0.003                          0.0    86.3100
5054                        0.003                          0.0    86.7800
5055                        0.003                          0.0    91.7900
5056                        0.003                          0.0    90.8000
5057                        0.003                          0.0    90.9000
5058                        0.003                          0.0    90.1200
5059                        0.003                          0.0    91.3600
5060                        0.003                          0.0    72.5145
5061                        0.001                          0.0    41.5800
5062                        0.001                          0.0    42.6700

In [2]:
#画出自然灾害的词云图
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import pandas as pd

# 读取 CSV 文件并创建 DataFrame 对象
df = pd.read_csv('/home/mw/project/Disaster.csv')

# 将所有单词拼接成字符串
text = ' '.join(df['Disaster Type'])

# 创建词云对象并生成词云
wc = WordCloud(background_color='white', width=800, height=600)
wc.generate(text)

plt.figure(dpi=300)
wc.to_file('./wordcloud.png')
# 显示词云图
plt.imshow(wc)
plt.axis('off')
plt.show()

In [49]:
import pandas as pd
import matplotlib.pyplot as plt
disa=pd.read_csv("/home/mw/project/Disaster.csv")
region_name=disa[["ISO"]].values
print(region_name)
t_sum={}
v=set()
for x in region_name:
    v.add(x[0])
for key in v:
    t_sum[key]=0
    
disa_s=disa.values
#统计各个国家的自然灾害发生次数
for x in disa_s:
    region=x[11]
    t_sum[region]=t_sum[region]+1
    pass
# 按值从大到小排序
sorted_d = sorted(t_sum.items(), key=lambda x: x[1], reverse=True)[:5]
top_ten=[]
for k,v in sorted_d:
    print(k)
    top_ten.append(k)
temp_ten=pd.read_csv("/home/mw/project/Temp000.csv").values
new=[]
plt.figure(figsize=(10,6))
plt.grid(True)
for e in temp_ten:
    if e[4] in top_ten:
        new.append(e)
year=['2000',"2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020"]
df = pd.DataFrame(new, columns=pd.read_csv("/home/mw/project/Temp000.csv").columns).values
marks=["h","s","^","x","o","d","<","p",">","+"]
i=0
for m in df:
    x=year
    y=m[11:]
    plt.plot(x,y,marker=marks[i],label=m[4])
    i=i+1
plt.title("自然灾害发生频率位于前5的国家的温度变化")
plt.legend()
plt.show()

[['CHN']
 ['AFG']
 ['BGD']
 ...
 ['ZWE']
 ['TLS']
 ['SSD']]
CHN
USA
IND
IDN
PHL